# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/c3s.ado.repertoire

db:
  image: postgres:9.4
  volumes:
    - ./postgresql-data:/var/lib/postgresql/data

tryton:
  build: Dockerfiles/tryton
  command: ado-do deploy-tryton
  volumes:
    - ./ado:/ado
  ports:
    - "8000:8000"
    - "8069:8069"
  links:
    - db
  env_file:
    - ./tryton.env

portal:
  build: Dockerfiles/portal
  command: ado-do deploy-portal
  volumes:
    - ./ado:/ado
  ports:
    - "6543"
    - "51000:51000"   # for winpdb debugger, also see potal dockerfile
  links:
    - db
    - proxy
    - api
    - tryton
  env_file:
    - ./portal.env

processing:
  build: Dockerfiles/processing
  command: cron && tail -f /ado/tmp/repro.log &
  volumes:
    - ./ado:/ado
  links:
    - tryton
  env_file:
    - ./processing.env

api:
  build: Dockerfiles/portal
  command: ado-do deploy-api
  volumes:
    - ./ado:/ado
  ports:
    - "6543"
  links:
    - db
    - proxy
  env_file:
    - ./api.env

proxy:
  build: Dockerfiles/nginx
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - "81:80"
