# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

services:

  database:
    # entrypoint: ["echo", "Service disabled in docker-compose.staging.yml."]
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql/data

  erpserver:
    ports:
      - "8000:8000"  # jsonrpc (tryton client)
      - "8069:8069"  # xmlrpc (proteus)
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  webserver:
    # entrypoint: ["echo", "Service disabled in docker-compose.staging.yml."]
    ports:
      - "80:80"  # http
    volumes:
      - ./volumes/nginx-certs:/etc/nginx/certs
      - ./volumes/nginx-dhparam:/etc/nginx/dhparam
      - ./volumes/nginx-htpasswd:/etc/nginx/htpasswd

  webapi:
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  webgui:
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  fingerprint:
    volumes:
      - ./volumes/echoprint-data:/opt/echoprint-data
