# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.2'
services:

  database:
    build: container/database
    image: cs_database
    volumes:
      - ./database:/var/lib/postgresql/data

  erpserver:
    build: container/erpserver
    image: cs_erpserver
    command: execute deploy-erpserver
    volumes:
      - ./shared:/shared
    ports:
      - "8000:8000"  # jsonrpc (tryton client)
      - "8069:8069"  # xmlrpc (proteus)
    depends_on:
      - database
    env_file:
      - ./environment/shared.env

  webserver:
    build: container/webserver
    image: cs_webserver
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "81:80"  # http
    logging:
      driver: none

  webapi:
    build: container/webapi
    image: cs_webapi
    command: execute deploy-webapi
    volumes:
      - ./shared:/shared
    ports:
      - "6543"  # pyramid pserve
    depends_on:
      - database
      - webserver
    env_file:
      - ./environment/shared.env
      - ./environment/webapi.env

  webgui:
    build: container/webgui
    image: cs_webgui
    command: execute deploy-webgui
    volumes:
      - ./shared:/shared
    ports:
      - "6543"  # pyramid pserve
    depends_on:
      - database
      - webserver
      - webapi
      - erpserver
      - browser
    env_file:
      - ./environment/shared.env
      - ./environment/webgui.env

  worker:
    build: container/worker
    image: cs_worker
    cpu_percent: 50
    mem_limit: 500m
    #command: cron && tail -f /shared/tmp/repro.log &
    command: bash -c "while true; do cd /shared/src/collecting_society_worker && python repro.py all; sleep 60; done"
    volumes:
      - ./shared:/shared
    depends_on:
      - erpserver
    env_file:
      - ./environment/shared.env
      - ./environment/worker.env

  browser:
    build: container/browser
    image: cs_browser
    volumes:
      - ./shared:/shared
      - /dev/shm:/dev/shm
