# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.2'
services:

  nginx:
    build: Dockerfiles/nginx
    image: c3s_repertoire_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "81:80"
    logging:
      driver: none

  db:
    build: ./Dockerfiles/db
    image: c3s_repertoire_db
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  tryton:
    build: Dockerfiles/tryton
    image: c3s_repertoire_tryton
    command: execute deploy-tryton
    volumes:
      - ./shared:/shared
    ports:
      - "8000:8000"
      - "8069:8069"
    depends_on:
      - db
    env_file:
      - ./tryton.env

  api:
    build: Dockerfiles/api
    image: c3s_repertoire_api
    command: execute deploy-api
    volumes:
      - ./shared:/shared
    ports:
      - "6543"
      - "51001:51001"   # for debugger
    depends_on:
      - db
      - nginx
    env_file:
      - ./api.env

  portal:
    build: Dockerfiles/portal
    image: c3s_repertoire_portal
    command: execute deploy-portal
    volumes:
      - ./shared:/shared
    ports:
      - "6543"
      - "51000:51000"   # for debugger
    depends_on:
      - db
      - nginx
      - api
      - tryton
      - selenium
    env_file:
      - ./portal.env

  processing:
    build: Dockerfiles/processing
    image: c3s_repertoire_processing
    cpu_percent: 50
    mem_limit: 500m
    #command: cron && tail -f /shared/tmp/repro.log &
    command: bash -c "while true; do cd /shared/src/collecting_society_worker && python repro.py all; sleep 60; done"
    volumes:
      - ./shared:/shared
    ports:
      - "51002:51002"   # for debugger
    depends_on:
      - tryton
    env_file:
      - ./processing.env

  selenium:
    build: Dockerfiles/selenium
    image: c3s_repertoire_selenium
    volumes:
      - ./shared:/shared
      - /dev/shm:/dev/shm
    env_file:
      - ./selenium.env

