# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

volumes:
  collecting_society_postgresql_data:
  collecting_society_echoprint_data:
  collecting_society_trytond_files:
  collecting_society_nginx_certs:
  collecting_society_nginx_dhparam:

services:

  webserver:
    volumes:
      - collecting_society_nginx_certs:/etc/nginx/certs
      - collecting_society_nginx_dhparam:/etc/nginx/dhparam

  database:
    volumes:
      - collecting_society_postgresql_data:/var/lib/postgresql/data

  erpserver:
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  webapi:
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  webgui:
    volumes:
      - collecting_society_trytond_files:/var/lib/trytond

  fingerprint:
    volumes:
      - collecting_society_echoprint_data:/opt/echoprint-data
