# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

volumes:
  postgresql-data:
  trytond-files:

services:

  database:
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  erpserver:
    volumes:
      - trytond-files:/var/lib/trytond

  worker:
    cpu_percent: 50
    mem_limit: 500m
