# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'
services:

  database:
    build:
      context: ./services/build
      target: database
      args: &buildargs
        ENVIRONMENT: ${ENVIRONMENT}
        APT_CACHERURL: ${APT_CACHERURL}
        APT_REFRESH: ${APT_REFRESH}
        WORKDIR: /shared
        DEBIAN: ${DEBIAN}
        DEBUGGER_WINPDB: ${DEBUGGER_WINPDB}
        DEBUGGER_PTVSD: ${DEBUGGER_PTVSD}
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql/data

  erpserver:
    build:
      context: ./services/build
      target: erpserver
      args: *buildargs
    command: execute deploy-erpserver
    volumes:
      - ./volumes/shared:/shared
      - ./volumes/trytond-files:/var/lib/trytond
    ports:
      - "8000:8000"  # jsonrpc (tryton client)
      - "8069:8069"  # xmlrpc (proteus)
    depends_on:
      - database
    env_file:
      - .env

  webserver:
    build:
      context: ./services/build
      target: webserver
      args: *buildargs
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "81:80"  # http
    logging:
      driver: none

  webapi:
    build:
      context: ./services/build
      target: webapi
      args: *buildargs
    command: execute deploy-webapi
    volumes:
      - ./volumes/shared:/shared
    ports:
      - "6543"  # pyramid pserve
    depends_on:
      - database
      - webserver
    env_file:
      - .env
      - environment/webapi.env

  webgui:
    build:
      context: ./services/build
      target: webgui
      args: *buildargs
    command: execute deploy-webgui
    volumes:
      - ./volumes/shared:/shared
    ports:
      - "6543"  # pyramid pserve
    depends_on:
      - database
      - webserver
      - webapi
      - erpserver
      - browser
    env_file:
      - .env
      - environment/webgui.env

  worker:
    build:
      context: ./services/build
      target: worker
      args: *buildargs
    cpu_percent: 50
    mem_limit: 500m
    #command: cron && tail -f /shared/tmp/repro.log &
    command: bash -c "while true; do cd /shared/src/collecting_society_worker && python repro.py all; sleep 60; done"
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      - erpserver
    env_file:
      - .env
      - environment/worker.env

  browser:
    build:
      context: ./services/build
      target: browser
      args: *buildargs
    volumes:
      - ./volumes/shared:/shared
      - /dev/shm:/dev/shm

volumes:
  collecting_society_aptcacher:
