# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/c3s.ado.repertoire

version: '2'
services:

  nginx:
    build: Dockerfiles/nginx
    image: c3s_repertoire_nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "81:80"

  db:
    build: ./Dockerfiles/db
    image: c3s_repertoire_db            
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

  tryton:
    build: Dockerfiles/tryton
    image: c3s_repertoire_tryton
    command: ado-do deploy-tryton
    volumes:
      - ./ado:/ado
    ports:
      - "8000:8000"
      - "8069:8069"
    links:
      - db
    env_file:
      - ./tryton.env

  api:
    build: Dockerfiles/api
    image: c3s_repertoire_api
    command: ado-do deploy-api
    volumes:
      - ./ado:/ado
    ports:
      - "6543"
      - "51000:51000"   # for winpdb debugger, also see portal dockerfile
    links:
      - db
      - nginx
    env_file:
      - ./api.env

  portal:
    build: Dockerfiles/portal
    image: c3s_repertoire_portal
    command: ado-do deploy-portal
    volumes:
      - ./ado:/ado
    ports:
      - "6543"
    #  - "51000:51000"   # for winpdb debugger, also see portal dockerfile
    links:
      - db
      - nginx
      - api
      - tryton
    env_file:
      - ./portal.env

  processing:
    build: Dockerfiles/processing
    image: c3s_repertoire_processing
    #command: cron && tail -f /ado/tmp/repro.log &
    command: bash -c "while true; do cd /ado/src/c3sRepertoireProcessing && python repro.py all; sleep 60; done"
    volumes:
      - ./ado:/ado    
    #ports:
    #  - "51000:51000"   # for winpdb debugger, also see processing dockerfile
    links:
      - tryton
    env_file:
      - ./processing.env
