# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

services:

  database:
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql/data

  erpserver:
    ports:
      - "8069:8069"  # xmlrpc (proteus)
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  webserver:
    volumes:
      - ./volumes/nginx-certs:/etc/nginx/certs
      - ./volumes/nginx-dhparam:/etc/nginx/dhparam

  webapi:
    ports:
      - "6544:6543"  # pyramid pserve
      - "51001:51001"  # debugger
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  webgui:
    ports:
      - "6543:6543"  # pyramid pserve
      - "51000:51000"  # debugger
    volumes:
      - ./volumes/trytond-files:/var/lib/trytond

  worker:
    ports:
      - "51002:51002"  # debugger

  fingerprint:
    ports:
      - "8080:8080"  # http
      - "51004:51004"  # debugger
    volumes:
      - ./volumes/shared:/shared
      - ./volumes/echoprint-data:/opt/echoprint-data
