# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

networks:
  frontend:
  backend:

volumes:
  test_postgresql_data:
  test_echoprint_data:
  test_trytond_files:

services:

  test_database:
    build:
      context: ./services/build
      target: database
      args: &buildargs
        ENVIRONMENT: ${ENVIRONMENT}
        APT_CACHERURL: ${APT_CACHERURL}
        WORKDIR: ${WORKDIR}
        DEBIAN: ${DEBIAN}
        DEBUGGER_WINPDB: ${DEBUGGER_WINPDB}
        DEBUGGER_PTVSD: ${DEBUGGER_PTVSD}
    networks:
      - backend
    healthcheck:
      test: /shared/healthcheck/database
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/shared:/shared
      - test_postgresql_data:/var/lib/postgresql/data
    environment:
      SERVICE: database

  test_erpserver:
    build:
      context: ./services/build
      target: erpserver
      args: *buildargs
    command: service-deploy
    networks:
      - backend
    healthcheck:
      test: /shared/healthcheck/erpserver
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      test_database:
        condition: service_healthy
      test_fingerprint:
        condition: service_started
    env_file:
      - .env
    environment:
      SERVICE: erpserver
      ENVIRONMENT: testing
      POSTGRES_HOSTNAME: test_database

  test_web:
    build:
      context: ./services/build
      target: webgui
      args: *buildargs
    command: tail -f /dev/null
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:51003:51003"  # debugger
    volumes:
      - ./volumes/shared:/shared
      - test_trytond_files:/var/lib/trytond
    depends_on:
      test_database:
        condition: service_healthy
    env_file:
      - .env
      - services/webapi.env
      - services/webgui.env
    environment:
      SERVICE: webgui
      ENVIRONMENT: testing
      TRYTON_HOSTNAME: test_erpserver
      POSTGRES_HOSTNAME: test_database
      API_C3SUPLOAD_URL: http://test_web:6545/repertoire
      API_C3SUPLOAD_CORS_ORIGINS: http://test_web:6544
      API_DATATABLES_URL: http://test_web:6545/datatables
      API_DATATABLES_CORS_ORIGINS: http://test_web:6544
      API_C3SMEMBERSHIP_URL: http://test_web:6545/c3smembership

  test_worker:
    build:
      context: ./services/build
      target: worker
      args: *buildargs
    cpu_percent: 50
    mem_limit: 500m
    command: service-deploy
    healthcheck:
      test: /shared/healthcheck/worker
      interval: 5m
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      test_erpserver:
        condition: service_healthy
      test_fingerprint:
        condition: service_started
    env_file:
      - .env
      - services/worker.env
    environment:
      SERVICE: worker
      ENVIRONMENT: testing
      TRYTON_HOSTNAME: test_erpserver
      POSTGRES_HOSTNAME: test_database
      ECHOPRINT_HOSTNAME: test_fingerprint
      DEBUGGER_WINPDB: 0
      DEBUGGER_PTVSD: 0

  test_browser:
    build:
      context: ./services/build
      target: browser
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        APT_CACHERURL: ${APT_CACHERURL}
        WORKDIR: ${WORKDIR}
        DEBIAN: ${DEBIAN}
        DEBUGGER_WINPDB: ${DEBUGGER_WINPDB}
        DEBUGGER_PTVSD: ${DEBUGGER_PTVSD}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - frontend
    depends_on:
      test_web:
        condition: service_started
    environment:
      SERVICE: browser

  test_fingerprint:
    build:
      context: ./services/build
      target: fingerprint
      args: *buildargs
    command: service-deploy
    healthcheck:
      test: /shared/healthcheck/fingerprint
      interval: 5m
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/shared:/shared
      - test_echoprint_data:/opt/echoprint-data
    networks:
      - backend
    env_file:
      - .env
    environment:
      SERVICE: fingerprint
      ENVIRONMENT: testing
