# For copyright and license terms, see COPYRIGHT.rst (top level of repository)
# Repository: https://github.com/C3S/collecting_society_docker

version: '2.4'

networks:
  frontend:
  backend:

services:

  database:
    build:
      context: ./services/build
      target: database
      args: &buildargs
        ENVIRONMENT: ${ENVIRONMENT}
        APT_CACHERURL: ${APT_CACHERURL}
        WORKDIR: ${WORKDIR}
        DEBIAN: ${DEBIAN}
        DEBUGGER_WINPDB: ${DEBUGGER_WINPDB}
        DEBUGGER_PTVSD: ${DEBUGGER_PTVSD}
    healthcheck:
      test: /shared/healthcheck/database
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/shared:/shared
    networks:
      - backend
    environment:
      SERVICE: database

  erpserver:
    build:
      context: ./services/build
      target: erpserver
      args: *buildargs
    command: service-deploy
    networks:
      - backend
    healthcheck:
      # test: /shared/healthcheck/erpserver
      test: service-healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      database:
        condition: service_healthy
      fingerprint:
        condition: service_started
    env_file:
      - .env
    environment:
      SERVICE: erpserver

  webserver:
    build:
      context: ./services/build
      target: webserver
      args: *buildargs
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    logging:
      driver: none
    environment:
      SERVICE: webserver

  webapi:
    build:
      context: ./services/build
      target: webapi
      args: *buildargs
    command: service-deploy
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      database:
        condition: service_healthy
      webserver:
        condition: service_started
    env_file:
      - .env
      - services/webapi.env
    environment:
      SERVICE: webapi

  webgui:
    build:
      context: ./services/build
      target: webgui
      args: *buildargs
    command: service-deploy
    networks:
      - frontend
      - backend
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      webapi:
        condition: service_started
    env_file:
      - .env
      - services/webgui.env
    environment:
      SERVICE: webgui

  worker:
    build:
      context: ./services/build
      target: worker
      args: *buildargs
    cpu_percent: 50
    mem_limit: 500m
    command: service-deploy
    networks:
      - backend
    volumes:
      - ./volumes/shared:/shared
    depends_on:
      erpserver:
        condition: service_healthy
      fingerprint:
        condition: service_started
    env_file:
      - .env
      - services/worker.env
    environment:
      SERVICE: worker

  fingerprint:
    build:
      context: ./services/build
      target: fingerprint
      args: *buildargs
    command: service-deploy
    networks:
      - backend
    volumes:
      - ./volumes/shared:/shared
    env_file:
      - .env
    environment:
      SERVICE: fingerprint
