---
#==============================================================================
# production config
#==============================================================================
production:

  # command config ------------------------------------------------------------
  commands:
    # update command
    update:
      # pull project container
      self: false
      # build images on changes
      images: false
      # migrate database on changes
      database: false
      # print header and footer
      extended: true


  # task config ---------------------------------------------------------------
  tasks:
    # update command
    update: &update
      # update main repository
      - name: ${PROJECT}_docker
        actions: ['repo_update', 'script_restart']
        target: '.'
        source: 'git@github.com:C3S/collecting_society_docker.git'
        version: '${BRANCH}'
        upstream: false
      # create basic folder structure
      - name: create basic folder structure
        actions: ['folder_create']
        batch:
          - name: 'code'
          - name: 'volumes/shared/tmp'
          - name: 'volumes/shared/tmp/logs'
      # update upstream repos
      - name: update upstream repos
        actions: ['repo_update']
        targetpath: 'volumes/shared/src'
        batch:
          - name: trytond
            source: 'https://github.com/tryton/trytond.git'
            version: '${TRYTON_VERSION}'
          - name: country
            source: 'https://github.com/tryton/country.git'
            version: '${TRYTON_VERSION}'
          - name: currency
            source: 'https://github.com/tryton/currency.git'
            version: '${TRYTON_VERSION}'
          - name: party
            source: 'https://github.com/tryton/party.git'
            version: '${TRYTON_VERSION}'
          - name: company
            source: 'https://github.com/tryton/company.git'
            version: '${TRYTON_VERSION}'
          - name: product
            source: 'https://github.com/tryton/product.git'
            version: '${TRYTON_VERSION}'
          - name: account
            source: 'https://github.com/tryton/account.git'
            version: '${TRYTON_VERSION}'
          - name: account_product
            source: 'https://github.com/tryton/account_product.git'
            version: '${TRYTON_VERSION}'
          - name: account_invoice
            source: 'https://github.com/tryton/account_invoice.git'
            version: '${TRYTON_VERSION}'
          - name: account_invoice_line_standalone
            source: 'https://github.com/tryton/account_invoice_line_standalone.git'
            version: '${TRYTON_VERSION}'
          - name: bank
            source: 'https://github.com/tryton/bank.git'
            version: '${TRYTON_VERSION}'
          - name: account_de_skr03
            source: 'https://github.com/tryton/account_de_skr03.git'
            version: '${TRYTON_VERSION}'
          - name: web_user
            source: 'https://github.com/virtualthings/web_user.git'
            version: '${TRYTON_VERSION}'
          - name: echoprint-codegen
            source: 'https://github.com/spotify/echoprint-codegen.git'
            version: 'master'
      # update project repos
      - name: update project repos
        actions: ['repo_update']
        targetpath: 'volumes/shared/src'
        upstream: false
        version: '${BRANCH}'
        batch:
          - name: archiving
            source: 'git@github.com:C3S/archiving.git'
          - name: portal
            source: 'git@github.com:C3S/portal.git'
          - name: collecting_society
            source: 'git@github.com:C3S/collecting_society.git'
          - name: portal_web
            source: 'git@github.com:C3S/portal_web.git'
          - name: collecting_society_web
            source: 'git@github.com:C3S/collecting_society_web.git'
          - name: collecting_society_worker
            source: 'git@github.com:C3S/collecting_society_worker.git'
          - name: echoprint-server
            source: 'git@github.com:C3S/echoprint-server.git'
            version: 'master'
      # copy and diff example files
      - name: copy and diff example files
        actions: ['file_copy', 'file_diff']
        batch:
          - name: .env
            ignore: ['^ENVIRONMENT', '^BRANCH=', '^GIT_SSH=', '^GIT_USER_NAME=', '^GIT_USER_EMAIL=']
          - name: services/webgui.env
            ignore: ['^PYRAMID_AUTHENTICATION_SECRET=', '^PYRAMID_SESSION_SECRET=']
          - name: services/webapi.env
            ignore: ['^PYRAMID_AUTHENTICATION_SECRET=', '^PYRAMID_SESSION_SECRET=']
          - name: services/worker.env
            ignore: ['^ECHOPRINT_TOKEN=', '^WORKER_PROTEUS_PASSWORD=']
          - name: volumes/shared/config/trytond/production.conf
            ignore: ['^privatekey =', '^certificate =', '^super_pwd =']
          - name: volumes/shared/config/trytond/staging.conf
            ignore: ['^privatekey =', '^certificate =', '^super_pwd =']
          - name: volumes/shared/src/collecting_society_worker/config.ini
            ignore: ['^srcpw =', '^destpw =']
      # copy tryton admin password example file
      - name: copy trytond admin password example file
        actions: ['file_copy']
        target: 'volumes/shared/config/trytond/passfile'
      # symlink docker override file
      - name: symlink docker override file
        actions: ['path_link']
        target: 'docker-compose.override.yml'
        source: 'docker-compose.production.yml'

    # diff command
    diff: *update

    # status command
    status: *update

    # pull command
    pull: *update

    # pull command
    commit: *update

    # push command
    push: *update

  # action config -------------------------------------------------------------
  actions:
    # update_repo action group
    repo_update: [
      git_clone, git_user, git_origin, git_status,
      git_fetch, git_checkout, git_track, git_pull
    ]
    # diff_file action
    file_diff:
      # regex for lines to be ignored in diffs
      ignore: [^#, ^\/\/, ^\n$]
    # git status action
    git_status:
      # use porcelain
      porcelain: true
    # git clone action
    git_clone:
      # create the conaining folder of the repo
      create_folder: true

#==============================================================================
# staging config, inherits from production
#==============================================================================
staging:
  tasks:
    update:
      # symlink docker override file
      - name: symlink docker override file
        source: 'docker-compose.staging.yml'

#==============================================================================
# testing config, inherits from staging
#==============================================================================
testing:
  config:
    update:
      images: true
      database: true
  tasks:
    update:
      # create folder for tests output
      - name: create folder for tests output
        target: 'volumes/shared/tests'
        actions: ['folder_create']
      # symlink docker override file
      - name: symlink docker override file
        source: 'docker-compose.${ENVIRONMENT}.yml'

#==============================================================================
# development config, inherits from testing
#==============================================================================
development:
  config:
    update:
      self: true
  tasks:
    update:
      # copy files for debugging
      - name: copy and diff example files
        batch:
          - name: '.devcontainer.json'
            ignore: []
      # symlink project repos
      - name: symlink project repos
        actions: ['path_link']
        targetpath: 'code'
        batch:
          - name: collecting_society
            source: 'volumes/shared/src/collecting_society'
          - name: portal_web
            source: 'volumes/shared/src/portal_web'
          - name: collecting_society_web
            source: 'volumes/shared/src/collecting_society_web'
          - name: echoprint-server
            source: 'volumes/shared/src/echoprint-server'
          - name: collecting_society_worker
            source: 'volumes/shared/src/collecting_society_worker'
      # checkout repos of pinned pip packages for reference
      - name: checkout repos of pinned pip packages for reference
        actions: ['git_clone', 'git_checkout']
        targetpath: 'volumes/shared/ref'
        batch:
          - name: click
            source: 'https://github.com/pallets/click.git'
            version: 'tags/4.0'
          - name: requests
            source: 'https://github.com/requests/requests.git'
            version: 'tags/v2.18.4'
          - name: psycopg2
            source: 'https://github.com/psycopg/psycopg2.git'
            version: 'tags/2_5_4'
          - name: proteus
            source: 'https://github.com/tryton/proteus.git'
            version: '${TRYTON_VERSION}'
          - name: webob
            source: 'https://github.com/Pylons/webob.git'
            version: 'tags/1.8.2'
          - name: pyramid
            source: 'https://github.com/Pylons/pyramid.git'
            version: 'tags/1.9.2'
          - name: pyramid_beaker
            source: 'https://github.com/Pylons/pyramid_beaker.git'
            version: 'tags/0.8'
          - name: pyramid_chameleon
            source: 'https://github.com/Pylons/pyramid_chameleon.git'
            version: 'tags/0.3'
          - name: pyramid_mailer
            source: 'https://github.com/Pylons/pyramid_mailer.git'
            version: 'tags/0.15.1'
          - name: colander
            source: 'https://github.com/Pylons/colander.git'
            version: 'tags/1.4'
          - name: cornice
            source: 'https://github.com/Cornices/cornice.git'
            version: 'tags/3.4.0'
          - name: cornice_swagger
            source: 'https://github.com/Cornices/cornice.ext.swagger.git'
            version: 'tags/0.7.0'
          - name: deform
            source: 'https://github.com/Pylons/deform.git'
            version: 'tags/2.0.5'
          - name: pydub
            source: 'https://github.com/jiaaro/pydub.git'
            version: 'tags/v0.22.0'
          - name: pytaglib
            source: 'https://github.com/supermihi/pytaglib.git'
            version: 'tags/v1.4.3'
          - name: pyechonest
            source: 'https://github.com/echonest/pyechonest.git'
            version: 'tags/9.0.0'
